# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='wisher',
            field=models.ManyToManyField(related_name='wishers', to='wishlist.User'),
        ),
    ]
