# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20170227_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='wishes',
            field=models.ManyToManyField(related_name='wishes', to='wishlist.User'),
        ),
    ]
