# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20170301_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='pending', max_length=40),
            preserve_default=False,
        ),
    ]
